
package org.donstu.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BankService", targetNamespace = "https://donstu.org/bank")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankService {


    /**
     * 
     * @return
     *     returns java.util.List<org.donstu.client.Employee>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAvailableEmployers", targetNamespace = "https://donstu.org/bank", className = "org.donstu.client.GetAvailableEmployers")
    @ResponseWrapper(localName = "getAvailableEmployersResponse", targetNamespace = "https://donstu.org/bank", className = "org.donstu.client.GetAvailableEmployersResponse")
    @Action(input = "https://donstu.org/bank/BankService/getAvailableEmployersRequest", output = "https://donstu.org/bank/BankService/getAvailableEmployersResponse")
    public List<Employee> getAvailableEmployers();

}
